### ISSUE TITLE
Last Played working for 10-20 seconds then returns 403

### ISSUE THREAD

**Issue by guilyx** [andyruwruw/andyruwruw#7]
Hello,

I set everything up and got it working (sort off), but am running into an issue: Currently Playing works fine and 100% of the time when a music is playing, but when I pause the music, Last Played only works for the first 10 seconds or so and then the GET requests returns a 403 status. I have no clue where it can come from, especially since the documentation doesn't mention this API call to return a 403. Any clue ?

**Comment by andyruwruw** [comment]
Interesting, 403 would be an authentication issue. I think I know what the problem is.

When creating your `refresh-token`, you have to clarify what [scopes](https://developer.spotify.com/documentation/general/guides/scopes/) it's authorized to use. You need to make sure you have `user-read-currently-playing` or `user-read-playback-state` for Now Playing. And `user-read-recently-played` for Recently Played. I think you may have not included the last one when creating the refresh token.

Last thing I'd check is to make sure your environmental variable is set up correctly. For private hosting, you'd want it to match [the .env example](https://github.com/andyruwruw/andyruwruw/blob/master/.env.example). For Vercel your environmental variables should look something like this.

<img width="393" alt="vercel" src="https://user-images.githubusercontent.com/46572910/123902116-1ab2b680-d921-11eb-8d39-674669179a7c.PNG">

Glad you're enjoying the README :)

Let me know if this resolves your issue

**Comment by guilyx** [comment]
Hi there, wasn't the scope. That was the very first thing I checked when I ran into the issue. But I did put a STATE environment variable with "random" as value. Removing that seems to have fixed it! 
Thanks!

**Comment by guilyx** [comment]
Oh well, this did the trick for about 3 hours.
If the credentials environment variables were an issue, last played wouldn't be the only thing failing right ? - but the scope seems right. It only seems to fail after a certain amount of time though.

**Comment by andyruwruw** [comment]
Yeah, it is strange that only the last played endpoint is broken.

Are you using the [provided endpoint](https://github.com/andyruwruw/andyruwruw/blob/master/api/login.ts) for authentication?. That's where `STATE` is used. Might be best to have that set before you use the endpoint.

If you use `refresh_token` from there that'd eliminate the chance that this is related to the token.

I should mention it's only built to run locally. If you drop into your local repo and run `vercel dev` that should run the serverless functions on `localhost:3000`, and you can go to `http://localhost:3000/api/login`.
